IF NOT EXISTS (SELECT 1 FROM pg_index WHERE indexrelid=to_regclass('public.users_email_lower_key') AND indisunique AND indisvalid AND indisready AND pg_get_indexdef(indexrelid)='CREATE UNIQUE INDEX users_email_lower_key ON public.users USING btree (lower(email)) WHERE (email IS NOT NULL)') THEN RAISE EXCEPTION 'CANONICAL_EMAIL_INDEX_INVALID'; END IF;
IF (SELECT count(*) FROM pg_index WHERE indexrelid IN (to_regclass('public.users_handle_casefold_unique'),to_regclass('public."Response_post_user_unique"'),to_regclass('public."Response_post_guest_unique"'),to_regclass('public."Response_post_guest_proof_unique"'),to_regclass('public."Answer_response_question_option_unique"'),to_regclass('public."Answer_response_question_text_unique"')) AND indisvalid AND indisready AND indisunique)<>6 THEN RAISE EXCEPTION 'INTEGRITY_INDEX_MISSING'; END IF;
IF (SELECT count(*) FROM public.handle_aliases)<>(SELECT count(*) FROM public.users)
 OR EXISTS (SELECT 1 FROM public.users u LEFT JOIN public.handle_aliases h ON h.handle=lower(u.handle) WHERE h.handle IS NULL OR h.user_id IS DISTINCT FROM CASE WHEN u.status='DELETED' THEN NULL ELSE u.id END)
THEN RAISE EXCEPTION 'HANDLE_BACKFILL_INVALID'; END IF;
IF EXISTS (SELECT 1 FROM public.security_email_outbox) OR EXISTS (SELECT 1 FROM public.deletion_decisions) THEN RAISE EXCEPTION 'UNEXPECTED_NEW_TABLE_WRITES'; END IF;
IF (SELECT count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relrowsecurity AND c.relname IN ('auth_sessions','oauth_accounts','oauth_states','otp_challenges','auth_rate_limits','OTPCode','PendingRegistration','user_mfa','auth_challenges','account_cleanup_jobs','handle_aliases','security_email_outbox','deletion_decisions'))<>13 THEN RAISE EXCEPTION 'SENSITIVE_RLS_MISSING'; END IF;
IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid='public.deletion_decisions'::regclass AND contype='f') THEN RAISE EXCEPTION 'JOURNAL_SUBJECT_FOREIGN_KEY'; END IF;
IF EXISTS (SELECT 1 FROM pg_roles r WHERE r.rolname IN ('anon','authenticated') AND (has_table_privilege(r.oid,'public.deletion_decisions','SELECT,INSERT,UPDATE,DELETE,TRUNCATE') OR has_table_privilege(r.oid,'public.security_email_outbox','SELECT,INSERT,UPDATE,DELETE,TRUNCATE') OR has_table_privilege(r.oid,'public.handle_aliases','SELECT,INSERT,UPDATE,DELETE,TRUNCATE'))) THEN RAISE EXCEPTION 'SENSITIVE_CLIENT_GRANT'; END IF;
