import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { auditConfiguration } from './capture.mjs';
import { CLI_SHA256,sha256,cleanEnvironment } from './contract.mjs';
const HERE=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(process.env.RELEASE18_TEST_ARTIFACT_ROOT??path.join(HERE,'../../../test-runs'));
fs.mkdirSync(root,{recursive:true,mode:0o700});
const cli=path.resolve(process.env.RELEASE18_TEST_CLI??path.join(process.cwd(),'.worktrees/account-settings/server/node_modules/prisma/build/index.js'));
test('actual locked JS CLI config baseline and private-cwd isolation from hostile parent config/package/dotenv',()=>{
  assert.equal(sha256(fs.readFileSync(cli)),CLI_SHA256);
  const ambient=fs.mkdtempSync(path.join(root,'cli-isolation-')),isolated=path.join(ambient,'private');
  fs.mkdirSync(isolated,{mode:0o700});
  const marker=path.join(ambient,'synthetic-hook-count.txt');
  fs.writeFileSync(path.join(ambient,'prisma.config.cjs'),"require('node:fs').appendFileSync("+JSON.stringify(marker)+",'SYNTHETIC_HOOK_RAN\\n'); module.exports = {};\n");
  fs.writeFileSync(path.join(ambient,'package.json'),JSON.stringify({private:true,prisma:{schema:'PARENT_SCHEMA_MUST_NOT_BE_USED.prisma'}}));
  fs.writeFileSync(path.join(ambient,'.env'),'PARENT_FILE_MUST_NOT_LOAD=postgresql://synthetic:synthetic@127.0.0.1:9/postgres\n');
  fs.writeFileSync(path.join(isolated,'package.json'),'{"private":true}\n');
  const schema=path.join(isolated,'schema.prisma');
  fs.writeFileSync(schema,'datasource db {\n provider = "postgresql"\n url = env("PARENT_FILE_MUST_NOT_LOAD")\n}\n');
  const env={...cleanEnvironment(process.env),HOME:ambient,USERPROFILE:ambient,TEMP:ambient,TMP:ambient};
  const invoke=(cwd,args)=>spawnSync(process.execPath,[cli,...args],{cwd,env,encoding:'utf8',windowsHide:true,timeout:90000,maxBuffer:65536,stdio:['ignore','pipe','pipe']});
  const baseline=invoke(ambient,['validate','--schema',schema]);
  fs.writeFileSync(path.join(ambient,'baseline-observation.json'),JSON.stringify({status:baseline.status,signal:baseline.signal,errorCode:baseline.error?.code??null,stdoutBytes:Buffer.byteLength(baseline.stdout??''),stderrBytes:Buffer.byteLength(baseline.stderr??''),markerObserved:fs.existsSync(marker),syntheticOnly:true})+'\n');
  assert(fs.existsSync(marker),'Actual CLI did not demonstrate the controlled config hook baseline');
  const countBefore=fs.readFileSync(marker,'utf8');
  assert.throws(()=>auditConfiguration(ambient,ambient),/AMBIENT_CONFIG_FILE_FORBIDDEN/);
  assert.doesNotThrow(()=>auditConfiguration(isolated,isolated));
  const isolatedRun=invoke(isolated,['validate','--schema',schema]);
  assert.equal(fs.readFileSync(marker,'utf8'),countBefore,'Parent config hook ran from isolated cwd');
  assert.equal(isolatedRun.status,1);
  const output=String(isolatedRun.stdout)+String(isolatedRun.stderr);
  assert(output.includes('Environment variable not found: PARENT_FILE_MUST_NOT_LOAD'),'Parent dotenv value must stay unavailable');
  assert(!output.includes('PARENT_SCHEMA_MUST_NOT_BE_USED'),'Parent package.prisma was consulted');
  fs.writeFileSync(path.join(ambient,'sanitized-observation.json'),JSON.stringify({platform:process.platform,cliSha256:CLI_SHA256,baselineExit:baseline.status,baselineSyntheticHookObserved:true,isolatedExit:isolatedRun.status,parentHookNotReexecuted:true,parentDotenvNotLoaded:true,parentPackagePrismaNotUsed:true,providerConnections:0,realCredentialsRead:false,scope:'Actual JS CLI validate/config behavior; not Linux or hosted transport proof'},null,2)+'\n');
});
